
project_id = "wxniywyujrxlwraocszi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbound_emails]
enabled = false

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54325
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["https://127.0.0.1:5173"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.medusa-products]
verify_jwt = false

[functions.medusa-cart]
verify_jwt = true

[functions.medusa-checkout]
verify_jwt = true

[functions.send-order-confirmation]
verify_jwt = false

[functions.notify-deal-subscribers]
verify_jwt = false

[functions.check-deal-notifications]
verify_jwt = false

[functions.newsletter-subscription]
verify_jwt = false

[functions.sync-contact-to-brevo]
verify_jwt = false

[functions.sync-deal-triggers-to-brevo]
verify_jwt = false

[analytics]
enabled = false

[functions.order-tracking-lookup]
verify_jwt = false

